# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: {{ .Release.Name }}-backend
