version: '3'

services:
  backend:
    image: my-backend-image:latest
    ports:
      - "5000:5000"
    networks:
      - myapp_network

  frontend:
    image: my-frontend-image:latest
    ports:
      - "5001:5001"
    networks:
      - myapp_network

networks:
  myapp_network:
    driver: overlay