apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: hello-world-pod
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world-container
    image: gcr.io/google-samples/hello-app:1.0
    ports:
    - containerPort: 8080
